# Generated by Django 4.2.5 on 2023-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("name", models.CharField(max_length=128)),
                ("price", models.FloatField(verbose_name="price")),
                ("sku", models.CharField(max_length=32)),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "product",
            },
        ),
    ]
