# Generated by Django 4.2.5 on 2023-09-10 04:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("brand", models.CharField(max_length=128)),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
            options={
                "verbose_name": "shipper",
                "verbose_name_plural": "shippers",
                "db_table": "shipper",
            },
        ),
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "InBound Scan"),
                            (1, "Scanned"),
                            (2, "In Transit"),
                            (3, "Transit"),
                            (4, "Delivery"),
                        ],
                        default=0,
                    ),
                ),
                ("destination_climate", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tracking",
                "verbose_name_plural": "tracking",
                "db_table": "tracking",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("delivery_date", models.DateTimeField(verbose_name="Delivery Date")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipment.shipper",
                    ),
                ),
                (
                    "tracking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment",
                        to="shipment.tracking",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "db_table": "shipment",
            },
        ),
    ]
