# Generated by Django 4.2.5 on 2023-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="seller_lead_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Seller Lead Time"
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="seller_rate",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Rate"),
        ),
    ]
