# Generated by Django 4.2.5 on 2023-09-10 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_customer_postal_code_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "address", "verbose_name_plural": "addresses"},
        ),
        migrations.AlterModelTable(
            name="address",
            table="address",
        ),
    ]
