# Generated by Django 4.2.5 on 2023-09-10 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_address_address_remove_address_city_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
