# Generated by Django 4.2.5 on 2023-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_customer_city"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="retailer",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
