# Generated by Django 4.2.5 on 2023-09-11 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_customer_managers_alter_retailer_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
