# Generated by Django 4.2.5 on 2023-09-11 12:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_customer_date_joined_customer_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="retailer",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
