# Generated by Django 4.2.5 on 2023-09-11 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("order", "0004_remove_order_quantity_orderdetail_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderDetail",
            new_name="OrderProduct",
        ),
    ]
