# Generated by Django 4.2.5 on 2023-09-11 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_rename_orderdetail_orderproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "order product",
                "verbose_name_plural": "order products",
            },
        ),
        migrations.AlterModelTable(
            name="orderproduct",
            table="order_product",
        ),
    ]
